apiVersion: v1
kind: Pod
metadata:
  name: stress-video1
spec:
  nodeName: drs-node01
  containers:
  - name: stress
    image: polinux/stress
    args:
    - stress
    - --cpu
    - "2"
    - -t
    - "120s"
    # resources:
    #   limits:
    #     cpu: 500m
    #   requests:
    #     cpu: 500m
  restartPolicy: OnFailure
