apiVersion: v1
kind: Pod
metadata:
  name: stress-disk
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: polinux/stress
    args:
    - stress
    - --hdd
    - "1"
    - --hdd-bytes
    - "256K"
    - -t
    - "240s"
    # resources:
    #   limits:
    #     cpu: 2000m
    #   requests:
    #     cpu: 2000m
  restartPolicy: OnFailure
