apiVersion: v1
kind: Pod
metadata:
  name: stress-video
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: polinux/stress
    args:
    - --cpu
    - "2"
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
  restartPolicy: OnFailure
