apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: network
spec:
  minAvailable: 1
  schedulerName: volcano
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: job
      template:
        metadata:
          name: stress
        spec:
          restartPolicy: OnFailure
          containers:
          - name: stress
            image: utkudarilmaz/hping3
            command: ["/bin/sh", "-c", "--"]
            args:
            - timeout 270s hping3 --udp --quiet --data 50 --interval u1000 192.168.3.131  # hping3 target host ip address
