apiVersion: v1
kind: Pod
metadata:
  name: stress-net
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: utkudarilmaz/hping3
    command: ["/bin/sh", "-c", "--"]
    args:
    - timeout 270s hping3 --udp --quiet --data 50 --interval u1000 192.168.3.131  # hping3 target host ip address
  restartPolicy: OnFailure