apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  runtimeClassName: nvidia
  containers:
    - name: cuda-container
      image: nvidia/cuda:12.0.1-cudnn8-devel-ubuntu22.04
      command: ["/bin/bash", "-c", "--"]
      args:
        - sleep 36000
      resources:
        requests:
          nvidia.com/gpu: 1
        limits:
          nvidia.com/gpu: 1