apiVersion: v1
kind: Pod
metadata:
  name: test-cephfs-pod-1
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/test
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: cephfs-pvc

---
apiVersion: v1
kind: Pod
metadata:
  name: test-cephfs-pod-2
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/test
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: cephfs-pvc