apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
type: Opaque
stringData:
  name: myjfs
  metaurl: "redis://:mypassword@192.168.3.148:6379/1"
  storage: minio
  bucket: "http://192.168.3.148:9000/myjfs"
  access-key: minioadmin
  secret-key: minioadmin